dataset:
  name: "Generated"
  base_dir: /data/datasets/generated/replica_cad
  sequence: "baseline/apt_0"
  start: 0
  end: -1
  stride: 5
  desired_height: 680
  desired_width: 1200
  camera_params:
    crop_edge: 0
    cx: 319.5
    cy: 239.5
    fx: 320.0
    fy: 320.0
    image_height: 480
    image_width: 640
    png_depth_scale: 6553.5
  relative_pose: False
  device: "cuda"

nodes_constructor:
  mask_generator:
    model: "MobileSAM"
    weights_path: "/home/docker_user/bbq_weights/mobilesamv2/weight"
  dino_generator:
    model: "dinov2_vits14_reg_lc"
    load_size: 448
    stride: 7
    facet: "value"
    num_patches_h: 63
    num_patches_w: 113
  detections_assembler:
    mask_conf_threshold: 0.95
    mask_area_threshold: 500
    max_bbox_area_ratio: 0.75
    min_points_threshold: 150
    downsample_voxel_size: 0.025
    dbscan_remove_noise: True
    dbscan_eps: 0.05
    dbscan_min_points: 10
    image_area: 816000 # desired_height * desired_width
  objects_associator:
    merge_det_obj_spatial_sim_thresh: 0.01
    merge_det_obj_visual_sim_thresh: 0.5
    downsample_voxel_size: 0.025
    merge_interval: 20
    merge_objects_overlap_thresh: 0.7
    merge_objects_visual_sim_thresh: 0.4
  projector:
    num_views: 5
    top_k: 1
    desired_height: 680
    desired_width: 1200
  postprocessing:
    obj_min_points: 150
    obj_min_detections: 3
  output_path: "/home/docker_user/BeyondBareQueries/output/scenes/replica_cad"
  output_name_nodes: "baseline_apt_0.json"
  output_name_objects: "baseline_apt_0.pkl.gz"
